### ISSUE TITLE
Explodes on python 3

### ISSUE THREAD

**Issue by fake-name** [tarruda/python-autopxd#12]
```
durr@rwpscrape:/media/Storage/Scripts/crabbit/cheaders⟫ autopxd amqp.h
Traceback (most recent call last):
  File "/usr/local/bin/autopxd", line 11, in <module>
    load_entry_point('autopxd==1.1.2', 'console_scripts', 'autopxd')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/autopxd/__init__.py", line 358, in cli
    outfile.write(translate(infile.read(), infile.name))
  File "/usr/local/lib/python3.5/dist-packages/autopxd/__init__.py", line 348, in translate
    p.visit(parse(code, extra_cpp_args=extra_cpp_args, whitelist=whitelist))
  File "/usr/local/lib/python3.5/dist-packages/autopxd/__init__.py", line 323, in parse
    preprocessed = preprocess(code, extra_cpp_args=extra_cpp_args)
  File "/usr/local/lib/python3.5/dist-packages/autopxd/__init__.py", line 314, in preprocess
    result.append(proc.communicate(input=code.encode('utf-8'))[0])
AttributeError: 'bytes' object has no attribute 'encode'

```

Basically the normal python2 encoding things.

Basically, it's the issue fixed by https://github.com/tarruda/python-autopxd/pull/3

**Comment by fake-name** [comment]
As an alternative to that PR, you can fix it easily by opening the files in ASCII mode:

```
@click.command()
@click.argument('infile', type=click.File('r'), default=sys.stdin)
@click.argument('outfile', type=click.File('w'), default=sys.stdout)
def cli(infile, outfile):
    outfile.write(translate(infile.read(), infile.name))

```

instead of 

```

@click.command()
@click.argument('infile', type=click.File('rb'), default=sys.stdin)
@click.argument('outfile', type=click.File('wb'), default=sys.stdout)
def cli(infile, outfile):
    outfile.write(translate(infile.read(), infile.name))
```

**Comment by tarruda** [comment]
Hi

I haven't merged #3  yet because it doesn't pass 3.4 test. Perhaps you want to send another PR that fixes the problem for you?
