### ISSUE TITLE
'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by rabernat** [tarruda/python-autopxd#15]
Thanks for sharing this valuable tool.

I am trying to run autopxd on [this header](https://github.com/dengwirda/jigsaw-geo-matlab/blob/master/jigsaw/inc/jigsaw_jig_t.h)
```
 autopxd jigsaw_jig_t.h test.pxd
```

When I do so, I get the following error

```
Traceback (most recent call last):
  File "/Users/rpa/anaconda/envs/geo_scipy/bin/autopxd", line 11, in <module>
    sys.exit(cli())
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/autopxd/__init__.py", line 341, in cli
    outfile.write(translate(infile.read(), infile.name))
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/autopxd/__init__.py", line 333, in translate
    p.visit(parse(code, extra_cpp_args=['-I', extra_incdir]))
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/autopxd/__init__.py", line 319, in parse
    preprocessed = preprocess(code, extra_cpp_args=extra_cpp_args)
  File "/Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/autopxd/__init__.py", line 310, in preprocess
    result.append(proc.communicate(input=code.encode('utf-8'))[0])
AttributeError: 'bytes' object has no attribute 'encode'
```

And then, a second later, an additional error:
```
error: no such file or directory: 'c'
clang: warning: /Users/rpa/anaconda/envs/geo_scipy/lib/python3.6/site-packages/autopxd/include: 'linker' input unused [-Wunused-command-line-argument]
```

I am using python 3.6 via conda on Mac OS.

Any advice would be appreciated.

**Comment by rabernat** [comment]
Just realized this is a duplicate of #12. Sorry for the noise.
