### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by chtenb** [tarruda/python-autopxd#6]
```
$ autopxd.exe Include/MyHeader.h MyHeader.pxd
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\autopxd.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python34\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python34\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python34\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python34\lib\site-packages\autopxd\__init__.py", line 341, in cli
    outfile.write(translate(infile.read(), infile.name))
  File "c:\python34\lib\site-packages\autopxd\__init__.py", line 333, in translate
    p.visit(parse(code, extra_cpp_args=['-I', extra_incdir]))
  File "c:\python34\lib\site-packages\autopxd\__init__.py", line 319, in parse
    preprocessed = preprocess(code, extra_cpp_args=extra_cpp_args)
  File "c:\python34\lib\site-packages\autopxd\__init__.py", line 308, in preprocess
    ] + extra_cpp_args + ['-'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "c:\python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "c:\python34\lib\subprocess.py", line 1114, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I'm on windows 7, and the filenames passed to autopxd do exist!

**Comment by per42** [comment]
Is cpp in the path?

**Comment by chtenb** [comment]
What does `cpp` mean?

**Comment by per42** [comment]
cpp is the [C preprocessor](http://www.tutorialspoint.com/unix_commands/cpp.htm). It must be on your PATH.

On my system:
```cmd
C:\Users\Per\code>where cpp
C:\msys64\mingw64\bin\cpp.exe

C:\Users\Per\code>echo const char *version = __VERSION__; | cpp
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
const char *version = "6.3.0";
```

I use MinGW-w64 in [MSYS2](http://www.msys2.org/)
